name: momentum
description: A super powerful flutter state management library inspired with MVC pattern with a very flexible dependency injection.
version: 1.2.9
homepage: https://github.com/xamantra/momentum
